AWSTemplateFormatVersion: version date

Description:
  String

Metadata:
  template metadata

Parameters:
  set of parameters

Rules:
  set of rules

Mappings:
  set of mappings

Conditions:
  set of conditions

Transform:
  set of transforms

Resources:
  ScriptTrackerECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ScriptTrackerECSCluster
      CapacityProviders:
        - FARGATE
        

Outputs:
  set of outputs
